
import Class.Question;
import Class.TestedUser;
import Class.User;
import java.awt.Panel;
import java.util.List;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Artjoms Vinokurovs
 */
public class TestingSystem extends javax.swing.JFrame {


    /**
     * Creates new form TestingSystem
     */
    public TestingSystem() {
        initComponents();
    }

    static final String DB_URL = " ";
    static final String DB_USER = "vino";
    static final String DB_PASSWD = "123456";   

    private ArrayList<User> users = new ArrayList();    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultPanel = new javax.swing.JPanel();
        ResultLabel = new javax.swing.JLabel();
        ProcentLable = new javax.swing.JLabel();
        PunktiLabel = new javax.swing.JLabel();
        RepeatButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        EndButton = new javax.swing.JButton();
        TestDialog1 = new javax.swing.JDialog();
        QuestionPanel = new javax.swing.JPanel();
        QuestionLable = new javax.swing.JLabel();
        AnswerPanel = new javax.swing.JPanel();
        AnswerButton1 = new javax.swing.JRadioButton();
        AnswerButton2 = new javax.swing.JRadioButton();
        AnswerButton3 = new javax.swing.JRadioButton();
        AnswerButton4 = new javax.swing.JRadioButton();
        NextButton = new javax.swing.JButton();
        HelpButton1 = new javax.swing.JButton();
        StartTestsPanel = new javax.swing.JPanel();
        TestNameLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        SartTestDutton = new javax.swing.JButton();
        HelpPanel = new javax.swing.JPanel();
        InformationLabel = new javax.swing.JLabel();
        RegistationHelpLabel = new javax.swing.JLabel();
        TestHelpLabel = new javax.swing.JLabel();
        TestSelection = new javax.swing.JPanel();
        TesteSelectionLable = new javax.swing.JLabel();
        TestButtonLvl1 = new javax.swing.JButton();
        TestButtonLvl2 = new javax.swing.JButton();
        RegistrtionDialog = new javax.swing.JDialog();
        RegistrationPanel = new javax.swing.JPanel();
        RegistrationWindowsLable = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        ParolLabel = new javax.swing.JLabel();
        RepeatParolLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        SurnameTextField = new javax.swing.JTextField();
        UserNameTextField = new javax.swing.JTextField();
        RegistrationButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        DBUser = new javax.swing.JPanel();
        ShowDB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        InputPanel = new javax.swing.JPanel();
        UserLogInLabel = new javax.swing.JLabel();
        ParolLogInLabel = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        sigInButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();

        ResultLabel.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        ResultLabel.setForeground(new java.awt.Color(102, 102, 255));
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLabel.setText("Rezultāti");

        ProcentLable.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        ProcentLable.setForeground(new java.awt.Color(102, 102, 255));
        ProcentLable.setText("Procenti:X%");

        PunktiLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        PunktiLabel.setForeground(new java.awt.Color(102, 102, 255));
        PunktiLabel.setText("Atzīme: n");

        RepeatButton.setBackground(new java.awt.Color(153, 153, 255));
        RepeatButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        RepeatButton.setForeground(new java.awt.Color(255, 255, 255));
        RepeatButton.setText("Mēģiniet vēlreiz");
        RepeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatButtonActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(153, 153, 255));
        SaveButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Saglabāt");

        EndButton.setBackground(new java.awt.Color(153, 153, 255));
        EndButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        EndButton.setForeground(new java.awt.Color(255, 255, 255));
        EndButton.setText("Beigt");
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultPanelLayout = new javax.swing.GroupLayout(ResultPanel);
        ResultPanel.setLayout(ResultPanelLayout);
        ResultPanelLayout.setHorizontalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProcentLable)
                            .addComponent(PunktiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EndButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(RepeatButton)
                .addGap(74, 74, 74))
        );
        ResultPanelLayout.setVerticalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProcentLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PunktiLabel)
                .addGap(18, 18, 18)
                .addComponent(RepeatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(EndButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TestDialog1.setBackground(new java.awt.Color(196, 223, 230));
        TestDialog1.setSize(new java.awt.Dimension(0, 0));

        QuestionPanel.setBackground(new java.awt.Color(102, 102, 255));

        QuestionLable.setBackground(new java.awt.Color(204, 204, 204));
        QuestionLable.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        QuestionLable.setForeground(new java.awt.Color(255, 255, 255));
        QuestionLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuestionLable.setText("Jautājums");

        javax.swing.GroupLayout QuestionPanelLayout = new javax.swing.GroupLayout(QuestionPanel);
        QuestionPanel.setLayout(QuestionPanelLayout);
        QuestionPanelLayout.setHorizontalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuestionPanelLayout.setVerticalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AnswerButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AnswerButton1.setForeground(new java.awt.Color(0, 59, 70));
        AnswerButton1.setText("jRadioButton1");
        AnswerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButton1ActionPerformed(evt);
            }
        });

        AnswerButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AnswerButton2.setForeground(new java.awt.Color(0, 59, 70));
        AnswerButton2.setText("jRadioButton2");
        AnswerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButton2ActionPerformed(evt);
            }
        });

        AnswerButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AnswerButton3.setForeground(new java.awt.Color(0, 59, 70));
        AnswerButton3.setText("jRadioButton3");
        AnswerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButton3ActionPerformed(evt);
            }
        });

        AnswerButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AnswerButton4.setForeground(new java.awt.Color(0, 59, 70));
        AnswerButton4.setText("jRadioButton4");
        AnswerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButton4ActionPerformed(evt);
            }
        });

        NextButton.setBackground(new java.awt.Color(153, 153, 255));
        NextButton.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Tālāk");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        HelpButton1.setBackground(new java.awt.Color(204, 0, 51));
        HelpButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HelpButton1.setForeground(new java.awt.Color(255, 255, 255));
        HelpButton1.setText("!");
        HelpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnswerPanelLayout = new javax.swing.GroupLayout(AnswerPanel);
        AnswerPanel.setLayout(AnswerPanelLayout);
        AnswerPanelLayout.setHorizontalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnswerPanelLayout.createSequentialGroup()
                        .addComponent(AnswerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(AnswerPanelLayout.createSequentialGroup()
                        .addComponent(AnswerButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HelpButton1)
                .addContainerGap())
            .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AnswerPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AnswerPanelLayout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(198, 198, 198))
                        .addGroup(AnswerPanelLayout.createSequentialGroup()
                            .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AnswerButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AnswerButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap()))))
        );
        AnswerPanelLayout.setVerticalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(HelpButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnswerButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerButton2)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AnswerPanelLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(AnswerButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(AnswerButton4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout TestDialog1Layout = new javax.swing.GroupLayout(TestDialog1.getContentPane());
        TestDialog1.getContentPane().setLayout(TestDialog1Layout);
        TestDialog1Layout.setHorizontalGroup(
            TestDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TestDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TestDialog1Layout.createSequentialGroup()
                        .addComponent(AnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TestDialog1Layout.setVerticalGroup(
            TestDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TestNameLabel.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        TestNameLabel.setForeground(new java.awt.Color(102, 102, 255));
        TestNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TestNameLabel.setText(" Nosaukums");

        WelcomeLabel.setBackground(new java.awt.Color(102, 102, 255));
        WelcomeLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Sveiki!");

        SartTestDutton.setBackground(new java.awt.Color(153, 153, 255));
        SartTestDutton.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        SartTestDutton.setForeground(new java.awt.Color(255, 255, 255));
        SartTestDutton.setText("Sākt testu");
        SartTestDutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SartTestDuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartTestsPanelLayout = new javax.swing.GroupLayout(StartTestsPanel);
        StartTestsPanel.setLayout(StartTestsPanelLayout);
        StartTestsPanelLayout.setHorizontalGroup(
            StartTestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartTestsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartTestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TestNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(StartTestsPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(SartTestDutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartTestsPanelLayout.setVerticalGroup(
            StartTestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartTestsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TestNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SartTestDutton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        InformationLabel.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        InformationLabel.setForeground(new java.awt.Color(102, 102, 255));
        InformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InformationLabel.setText("Informācija");

        RegistationHelpLabel.setBackground(new java.awt.Color(102, 102, 255));
        RegistationHelpLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        RegistationHelpLabel.setText("1.(Reģistrācijas palīdzība)");

        TestHelpLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        TestHelpLabel.setText("2.(Testu palīdzība)");

        javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
        HelpPanel.setLayout(HelpPanelLayout);
        HelpPanelLayout.setHorizontalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelpPanelLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TestHelpLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistationHelpLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        HelpPanelLayout.setVerticalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(RegistationHelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(TestHelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        TesteSelectionLable.setBackground(new java.awt.Color(102, 102, 255));
        TesteSelectionLable.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        TesteSelectionLable.setForeground(new java.awt.Color(102, 102, 255));
        TesteSelectionLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TesteSelectionLable.setText("Testu izvēlne");

        TestButtonLvl1.setBackground(new java.awt.Color(153, 153, 255));
        TestButtonLvl1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        TestButtonLvl1.setForeground(new java.awt.Color(255, 255, 255));
        TestButtonLvl1.setText("1. Tests");

        TestButtonLvl2.setBackground(new java.awt.Color(153, 153, 255));
        TestButtonLvl2.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        TestButtonLvl2.setForeground(new java.awt.Color(255, 255, 255));
        TestButtonLvl2.setText("2. Tests");
        TestButtonLvl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonLvl2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestSelectionLayout = new javax.swing.GroupLayout(TestSelection);
        TestSelection.setLayout(TestSelectionLayout);
        TestSelectionLayout.setHorizontalGroup(
            TestSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TesteSelectionLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TestSelectionLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(TestSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TestButtonLvl2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestButtonLvl1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        TestSelectionLayout.setVerticalGroup(
            TestSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TesteSelectionLable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TestButtonLvl1)
                .addGap(37, 37, 37)
                .addComponent(TestButtonLvl2)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        RegistrationPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.setToolTipText("");
        RegistrationPanel.setPreferredSize(new java.awt.Dimension(680, 552));

        RegistrationWindowsLable.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        RegistrationWindowsLable.setForeground(new java.awt.Color(102, 102, 255));
        RegistrationWindowsLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrationWindowsLable.setText("Reģistrācijas logs");

        NameLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Vārds:");

        SurnameLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        SurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SurnameLabel.setText("Uzvārds:");

        UserNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserNameLabel.setText("Lietotājvārds:");

        ParolLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        ParolLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ParolLabel.setText("Parole:");

        RepeatParolLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        RepeatParolLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RepeatParolLabel.setText("Parole (atkārtoti):");

        NameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        SurnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        UserNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RegistrationButton.setBackground(new java.awt.Color(204, 204, 204));
        RegistrationButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        RegistrationButton.setText("Reģistrēties");
        RegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationButtonActionPerformed(evt);
            }
        });

        HelpButton.setBackground(new java.awt.Color(204, 0, 51));
        HelpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HelpButton.setForeground(new java.awt.Color(255, 255, 255));
        HelpButton.setText("!");

        javax.swing.GroupLayout RegistrationPanelLayout = new javax.swing.GroupLayout(RegistrationPanel);
        RegistrationPanel.setLayout(RegistrationPanelLayout);
        RegistrationPanelLayout.setHorizontalGroup(
            RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addComponent(HelpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistrationWindowsLable, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPanelLayout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPanelLayout.createSequentialGroup()
                                .addComponent(RegistrationButton)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SurnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                    .addComponent(UserNameTextField)
                                    .addComponent(NameTextField)))))))
            .addGroup(RegistrationPanelLayout.createSequentialGroup()
                .addGroup(RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(SurnameLabel))
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(NameLabel))
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(UserNameLabel))
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(ParolLabel))
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(RepeatParolLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        RegistrationPanelLayout.setVerticalGroup(
            RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPanelLayout.createSequentialGroup()
                .addGroup(RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HelpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPanelLayout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(RegistrationWindowsLable)
                        .addGap(26, 26, 26)))
                .addComponent(SurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(UserNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(ParolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatParolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(RegistrationButton)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout RegistrtionDialogLayout = new javax.swing.GroupLayout(RegistrtionDialog.getContentPane());
        RegistrtionDialog.getContentPane().setLayout(RegistrtionDialogLayout);
        RegistrtionDialogLayout.setHorizontalGroup(
            RegistrtionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegistrtionDialogLayout.setVerticalGroup(
            RegistrtionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        ShowDB.setText("Show");
        ShowDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDBActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Nick Name", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout DBUserLayout = new javax.swing.GroupLayout(DBUser);
        DBUser.setLayout(DBUserLayout);
        DBUserLayout.setHorizontalGroup(
            DBUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
            .addGroup(DBUserLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(ShowDB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DBUserLayout.setVerticalGroup(
            DBUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DBUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(ShowDB)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 223, 230));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        InputPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        UserLogInLabel.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        UserLogInLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserLogInLabel.setText("Lietotājvārds");

        ParolLogInLabel.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        ParolLogInLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ParolLogInLabel.setText("Parole");
        ParolLogInLabel.setToolTipText("");

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        sigInButton.setBackground(new java.awt.Color(102, 102, 255));
        sigInButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        sigInButton.setForeground(new java.awt.Color(255, 255, 255));
        sigInButton.setText("Ielogoties");
        sigInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigInButtonMouseClicked(evt);
            }
        });
        sigInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigInButtonActionPerformed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(204, 204, 204));
        RegisterButton.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        RegisterButton.setText("Reģistrēties");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("LOGIN");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nav konta...");

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegisterButton))
                    .addComponent(ParolLogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLogInLabel)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(sigInButton)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(UserLogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParolLogInLabel)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sigInButton)
                .addGap(16, 16, 16)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(jLabel2))
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RepeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeatButtonActionPerformed

    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndButtonActionPerformed

    private void AnswerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButton1ActionPerformed

    }//GEN-LAST:event_AnswerButton1ActionPerformed

    private void AnswerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButton2ActionPerformed

    }//GEN-LAST:event_AnswerButton2ActionPerformed

    private void AnswerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButton3ActionPerformed

    }//GEN-LAST:event_AnswerButton3ActionPerformed

    private void AnswerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButton4ActionPerformed

    }//GEN-LAST:event_AnswerButton4ActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed

    }//GEN-LAST:event_NextButtonActionPerformed

    private void SartTestDuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SartTestDuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SartTestDuttonActionPerformed

    private void HelpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpButton1ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        RegistrtionDialog.setBounds(0, 0, 450, 450);
        RegistrtionDialog.setLocationRelativeTo(null);
        RegistrtionDialog.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void sigInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigInButtonActionPerformed

    }//GEN-LAST:event_sigInButtonActionPerformed

    private void ShowDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDBActionPerformed
        
    }//GEN-LAST:event_ShowDBActionPerformed

    private void sigInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigInButtonMouseClicked
        String username = tfUsername.getText();
        String password = new String(jPasswordField3.getPassword());
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username / Password should be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
         for (char i : jPasswordField3.getPassword()) {
            password += i;
        }

        signIn(username, password);
    }//GEN-LAST:event_sigInButtonMouseClicked

    private void TestButtonLvl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonLvl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestButtonLvl2ActionPerformed

    private void RegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationButtonActionPerformed
String password = "";
        String repeatPass = "";

        for (char i : jPasswordField2.getPassword()) {
            password += i;
        }
        for (char i : jPasswordField1.getPassword()) {
            repeatPass += i;
        }

        registration(NameTextField.getText(), SurnameTextField.getText(), UserNameTextField.getText(), password, repeatPass);       
    }//GEN-LAST:event_RegistrationButtonActionPerformed

    /**
     * @param args the command line arguments
     */   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingSystem().setVisible(true);
            }
        });
    }
   
    private void addUser(String name, String surname, String login, String password) {
        try {
            Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWD);
            Statement statement = connection.createStatement();
            
            statement.execute("INSERT INTO GRAVENON.USERS(name, surname, login, password) VALUES ('" + name + "', '" + surname + "', '" + login + "', '" + password + "')");
            
            
            TestedUser testedUser = new TestedUser(name, surname, login, password);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private User findUser(String login, String password) {
    for (User user : users) {
            if (user.getLogin().equals(login)) {
                return user;
            }
        }
        return null;
    }

    private void save() {

    }

    private void load() {

    }

    private void getResult() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnswerButton1;
    private javax.swing.JRadioButton AnswerButton2;
    private javax.swing.JRadioButton AnswerButton3;
    private javax.swing.JRadioButton AnswerButton4;
    private javax.swing.JPanel AnswerPanel;
    private javax.swing.JPanel DBUser;
    private javax.swing.JButton EndButton;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HelpButton1;
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JLabel InformationLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel ParolLabel;
    private javax.swing.JLabel ParolLogInLabel;
    private javax.swing.JLabel ProcentLable;
    private javax.swing.JLabel PunktiLabel;
    private javax.swing.JLabel QuestionLable;
    private javax.swing.JPanel QuestionPanel;
    private javax.swing.JLabel RegistationHelpLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JLabel RegistrationWindowsLable;
    private javax.swing.JDialog RegistrtionDialog;
    private javax.swing.JButton RepeatButton;
    private javax.swing.JLabel RepeatParolLabel;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JPanel ResultPanel;
    private javax.swing.JButton SartTestDutton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton ShowDB;
    private javax.swing.JPanel StartTestsPanel;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField SurnameTextField;
    private javax.swing.JButton TestButtonLvl1;
    private javax.swing.JButton TestButtonLvl2;
    private javax.swing.JDialog TestDialog1;
    private javax.swing.JLabel TestHelpLabel;
    private javax.swing.JLabel TestNameLabel;
    private javax.swing.JPanel TestSelection;
    private javax.swing.JLabel TesteSelectionLable;
    private javax.swing.JLabel UserLogInLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sigInButton;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    private void registration(String text, String text0, String text1, String password, String repeatPass) {
       
        if (!password.equals(repeatPass)) {
            JOptionPane.showMessageDialog(this,"Parole nesakrīt ", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (password.length() < 5) {
             JOptionPane.showMessageDialog(this,"Minimalais paroles garums ir 5 simboli", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        NameTextField.setText(" ");
        SurnameTextField.setText(" ");
        UserNameTextField.setText(" ");
        jPasswordField2.setText(" ");
        jPasswordField1.setText(" ");
    }
    
    private void signIn(String text, String password) {
        User user = findUser(text, password);

        setContentPane(TestSelection);
        setVisible(true);
        InputPanel.setVisible(false);

        tfUsername.setText("");
        jPasswordField3.setText("");
    }
}
